In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [7]:
df = pd.read_excel(r"C:\Users\HP\Downloads\salary_sheet.xlsx")

In [9]:
df

experience  test_score (out of 10)  interview_score(out of 10)  salary
0        NaN                     8.0                           9   50000
1        NaN                     8.0                           6   45000
2       five                     6.0                           7   60000
3        two                    10.0                          10   65000
4      seven                     9.0                           6   70000
5      three                     7.0                          10   62000
6        ten                     NaN                           7   72000
7     eleven                     7.0                           8   80000

In [11]:
df.experience = df.experience.fillna('zero')
df['experience']

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [13]:
 df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score (out of 10)  interview_score(out of 10)  salary
0           0                     8.0                           9   50000
1           0                     8.0                           6   45000
2           5                     6.0                           7   60000
3           2                    10.0                          10   65000
4           7                     9.0                           6   70000
5           3                     7.0                          10   62000
6          10                     NaN                           7   72000
7          11                     7.0                           8   80000

In [15]:
import math


In [17]:
meadian_score = math.floor(df['test_score (out of 10)'].median())

In [19]:
df['test_score (out of 10)'] = df['test_score (out of 10)'].fillna(meadian_score)

In [21]:
df['test_score (out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score (out of 10), dtype: float64

In [23]:
reg =  linear_model.LinearRegression()
reg.fit(df[['experience','test_score (out of 10)','interview_score(out of 10)']],df['salary'])

LinearRegression()

In [29]:
reg.predict([[0,10,10]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([58246.72489083])

In [31]:
reg.predict([[10,5,5]])

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([66121.54294032])

In [53]:
d = pd.read_excel(r"C:\Users\HP\Downloads\salery 1.xlsx")

In [55]:
d

experience  test_score (out of 10)  interview_score(out of 10)
0        NaN                       0                           9
1        NaN                       4                           8
2       five                       6                           7
3      seven                       5                           5
4        one                       6                           5
5      three                       7                          10
6       nine                       5                           3
7     eleven                       7                           8

In [65]:
d.experience = d.experience.fillna('zero')

In [67]:
d

experience  test_score (out of 10)  interview_score(out of 10)
0       zero                       0                           9
1       zero                       4                           8
2       five                       6                           7
3      seven                       5                           5
4        one                       6                           5
5      three                       7                          10
6       nine                       5                           3
7     eleven                       7                           8

In [69]:
d.experience = d.experience.apply(w2n.word_to_num)

In [81]:
d

experience  test_score (out of 10)  interview_score(out of 10)
0           0                       0                           9
1           0                       4                           8
2           5                       6                           7
3           7                       5                           5
4           1                       6                           5
5           3                       7                          10
6           9                       5                           3
7          11                       7                           8

In [89]:
 new = reg.predict(d)

In [91]:
d["salary"] = new

In [93]:
new

array([37584.42503639, 42762.00873362, 58312.95487627, 57682.6783115 ,
       42650.65502183, 61148.47161572, 58898.1077147 , 79241.63027656])

In [95]:
d

experience  test_score (out of 10)  interview_score(out of 10)  \
0           0                       0                           9   
1           0                       4                           8   
2           5                       6                           7   
3           7                       5                           5   
4           1                       6                           5   
5           3                       7                          10   
6           9                       5                           3   
7          11                       7                           8   

         salary  
0  37584.425036  
1  42762.008734  
2  58312.954876  
3  57682.678311  
4  42650.655022  
5  61148.471616  
6  58898.107715  
7  79241.630277

In [99]:
d.to_excel('new_predicated.xlsx')